NDefines.NEconomy.FORT_CONSUMED_IN_SETTLEMENT_CONTRUCTION = 0
NDefines.NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_STANDARD = 0.00
NDefines.NCharacter.TREASURY_CHANCE_TO_DISAPPEAR_NO_HEIR = 0.0

NDefines.NMilitary.LIGHT_INFANTRY_PHASE_PURSUE_ATTACK = 3
NDefines.NMilitary.HEAVY_INFANTRY_PHASE_PURSUE_ATTACK = 2
NDefines.NMilitary.PIKEMEN_PHASE_PURSUE_ATTACK = 0.4
NDefines.NMilitary.LIGHT_CAVALRY_PHASE_PURSUE_ATTACK = 7
NDefines.NMilitary.KNIGHTS_PHASE_PURSUE_ATTACK = 5
NDefines.NMilitary.ARCHERS_PHASE_PURSUE_ATTACK = 3
NDefines.NMilitary.SPECIAL_TROOPS_PHASE_PURSUE_ATTACK = 8